# Use the official Node.js image as the base image
FROM node:14-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY ./client/package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY ./client/ .

# Build the application
#RUN npm run build
#RUN npm run serve

# Set the command to start the application
CMD [ "npm", "run", "serve" ]

# Expose the port used by the application
EXPOSE 8085
