FROM python:3.10

# (Roman) Si kopcil tie fily rovno pod `/`, vacsinou sa to dava pod
#         `/app`.
COPY requirements.txt /app/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt

COPY download_mitre01.py /app/

WORKDIR /app

CMD [ "python", "-u", "/app/download_mitre01.py"]