version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/engine
    ports:
      - "80:80"
    depends_on:
      - db
      - python

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile_vue
    volumes: 
      - .:/client
    ports:
      - "8085:8080"
    depends_on:
      - web
      

  db:
    # (Roman) Vzdy je dobre pinnut verziu, lebo default je :latest a to je total zlo. Mozno
    # mate ine verzie postgresu. Ak si chces byt na stopic isty, tak to mozes pinnut aj s hashom
    # odtialto https://hub.docker.com/_/postgres/tags?page=1&name=15
    # napr. postgres@sha256:6b91d38a9c596fa4e6a1276f6f81810882d9f292a09f9cf2647c6a554c8b6d00
    image: postgres:15.2
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    

  python:
    build:
      context: .
      dockerfile: Dockerfile_python
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db


volumes:
  db-data:
